name: att_dev_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.14
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - networkx
  - pydot
  - ase
  - rdkit
  - ipython
  - pyvis
  - pytest
  - pytest-cov
  - sphinx
  - sphinx-rtd-theme
  - pubchempy
  - cairosvg
  - pillow
  - pip:
      - dagviz
      - assemblycfg
      - assembly-theory
